version: "3.8"

services:
  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USERNAME: ${postgres}
      POSTGRES_PASSWORD: ${=;5&Aa}=zQ[F0s)H}
      POSTGRES_DB: ${provaWeb}